name: HACKPACK RUNNER

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Обновлено до v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Обновлено до v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiogram aiohttp

      - name: Run Bot
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Исправляет предупреждение Node.js
        run: python post.py
